version: '3'
services:
  client:
    image: love:2.0.1
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3008:3008"
    volumes:
      - .:/app
      - /app/node_modules
